### PR TITLE
Implemented Devconnect ticket authentication

### PR DESCRIPTION
**Pull request by pk910**
Implemented the `zupass` module, which provides the ability to authenticate with a devconnect ticket.

### CODE REVIEW

**Comment by pk910** [comment]
I think the Zupass SDK is too heavy to merge this into `master`.
I've already split out the zupass stuff into its own js file, as it literally adds 4.1MB minified js code to the fronted 🤯
I'll run this branch on the holesky & sepolia instances during the devconnect event and revert back afterwards.

**Review by Vtalike — APPROVED** [review]
Bot

**Comment by crisgarner** [comment]
@pk910 Is there a configuration for the Zupass module? Trying to run it locally, but seems it doesn't work

**Comment by pk910** [comment]
That's the zupass module config I'm currently using for the holesky/sepolia instances:
```
  ## Zupass protection
  zupass:
    enabled: true
    zupassUrl: "https://zupass.org/"
    zupassApiUrl: "https://api.zupass.org/"
    event:
      name: "Devconnect 2023"
      eventIds:
        - "785e8a0e-6734-11ee-b810-a2b83754f6bc" # AW Assembly
        - "0996f5fa-6736-11ee-a3bd-a2b83754f6bc" # Programmable Cryptography
        - "f626d630-2f8a-11ee-be83-b2dd9fd377ba" # 0xPARC Event
        - "a1c822c4-60bd-11ee-8732-763dbf30819c" # Devconnect Cowork Space
        - "3049870c-6cc8-11ee-98f3-7ebd6aca95cd" # Solidity Summit
        - "aebcb892-69e5-11ee-b65e-a2b83754f6bc" # EVM Summit
        - "7b57a8fc-6bae-11ee-bf2a-9e102a509962" # ETHconomics
        - "e1423686-6cc7-11ee-98f3-7ebd6aca95cd" # Next Billion
        - "140b208c-6d1d-11ee-8320-126a2f5f3c5e" # Wallet Unconference
    verify:
      signer: ["05e0c4e8517758da3a26c80310ff2fe65b9f85d89dfc9c80e6d0b6477f88173e", "29ae64b615383a0ebb1bc37b3a642d82d37545f0f5b1444330300e4c4eedba3f"]
    requireLogin: true
    concurrencyLimit: 1
    grants:
      - limitCount: 1
        duration: 63072000
        required: true
    infoHtml: |
      Benefits of authenticating with your devconnect ticket:<br>
      <ul>
        <li>Request <b>500 HolETH</b> once</li>
      </ul>
      Accepted Tickets:
      <ul>
        <li>Devconnect Cowork Space</li>
        <li>Autonomous Worlds Assembly</li>
        <li>Programmable Cryptography</li>
        <li>Solidity Summit</li>
        <li>EVM Summit</li>
        <li>ETHconomics</li>
        <li>Next Billion World Cafe</li>
        <li>Wallet Unconference</li>
      </ul>
```

**Comment by crisgarner** [comment]
Thanks! this helps

**Comment by minhtv28** [comment]
> Implemented the `zupass` module, which provides the ability to authenticate with a devconnect ticket.

good

**Comment by minhtv28** [comment]
gm

**Comment by pk910** [comment]
I've re-implemented the zupass module in #161.
closing this PR now.

**Pull request closed without merging**
