### PR TITLE
Revert "Fix: typos"

### PR DESCRIPTION
**Pull request by hargooth123**
`Reverts` pk910/PoWFaucet#19

### CODE REVIEW

**Comment by pk910** [comment]
Why?

**Comment by raaffee** [comment]
Currently I am facing some problem I am stacked with that that’s why.

**Comment by pk910** [comment]
What problem are you facing that needs reverting a typo fix commit?
I've even added a fallback, so legacy configs with that typo inside still work...

And why does a completely unrelated account reply this and not the original one?
Looks like spam to me...

**Comment by raaffee** [comment]
I fixed it.

**Comment by pk910** [comment]
Lol, I'm actually getting really confused by that stuff :D
Is it called "parallelization" or "paralellization"

**Pull request closed without merging**
